### ISSUE TITLE
Make weekly/daily/monthly reports configurable

### ISSUE THREAD

**Issue by jlark** [GreatLakesEnergy/sesh-dash-beta#349]
Currently there is a single email template. This should be made generic that any aggregate value can be put in it.

**Comment by jlark** [comment]
@upatricck please start thinking about this next. The idea is that you can have a an email report sent on a specific day every week or every day or on a specific day every month. 
This will be a setting for a site. The values sent in the email should be configurabe, (it could be pv_production + consumption) or just (pv_production). 

This might require changing the whole BOM_data_model to make it more generic.

**Comment by upatricck** [comment]
For the values to be configurable, the prepare_report function should be able to generate reports that are configurable based on specified values.

Since the values that we generate the reports from are from the Daily_Data_Point table, we would need a mapping that would specify which rows to of the daily data point instances to query for a given site.This would also need to specify the operation because in some cases the report are averages of the of the instances or in other cases are sums.

The prepare_report function would now use the daily_data_points provided for the duration (daily, week, month, or any other time interval). and then check the tooglled mappings for the site to generate the report for the field based on the operation(sum, average). The results would be added to a dict that would be looped over in the template.

Using a dict in the template for configurable values willl cause us to loose the language, For example: The total number of alerts is: value, The total energy produced is: value. would be replace by.
Number of alerts: value, 
Total Energy: value.

For now this is what i think we can use to make this configurable.

**Comment by jlark** [comment]
Initially, we need a new Model way to store specific report jobs that will need to be run so we need a new model.
Reports table might look like: Site_id (FK), duration (daily,weekly,monthly), Data-point (FK)

Initially Data-point can point to a fieldname within Daily-Data-Point, But I think that will be too rigid, it doesn't allow us to add new fields easily (we will need this for example for RTC coffee based data points). We need to go beyond daily data point. . I think this also needs to be expanded to be more flexible so new fields can be added that are daily data points. 

We can make do this by making the Daily Data Point like such making it not just daily but also configurable so we can have many different types for each site.
Data Point (model): site_id, time, length, duration, field_name, field_value 
(this might need more discussion, it's not exactly too clear in my head right now)

With respect to displaying the data in the email. We can have a bit more rigid structure to the email that uses a table to display the data with some natural language in the introduction for meta information like , site_name, duration and date.

I think we can start with the report model first.
